### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Kabi4**
I Remove rerendering of the header component and also make sure if user visit an unavailable page he redirects to home and also added to see projects in details by using dynamic routing

### CODE REVIEW

**Review by rohitdalvi18 — CHANGES_REQUESTED** [review]
Hey good work!
But since this is a **template** please remove all the links (or set value to '#') present in `Skills.js`.

**Comment by Kabi4** [comment]
Hey although these all are mine profile link but i have removed them :)

**Comment by Kabi4** [comment]
Happy if you let it merge now :)

**Comment by rohitdalvi18** [comment]
> Hey although these all are mine profile link but i have removed them :)

I know they are all your profile links, that's why I asked you to remove them since this is a **template**.

**Review by rohitdalvi18 — APPROVED** [review]

**Pull request merged**
